global:
  podSecurityPolicy:
    enabled: ${psp_enabled}
    useAppArmor: false

image:
  repository: "${container_registry}/cert-manager/cert-manager-controller"
  tag: "v1.0.4"
  pullPolicy: IfNotPresent

extraArgs:
  # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted
  - --enable-certificate-owner-ref=true

cainjector:
  image:
    repository: "${container_registry}/cert-manager/cert-manager-cainjector"
    tag: "v1.0.4"
    pullPolicy: IfNotPresent

webhook:
  image:
    repository: "${container_registry}/cert-manager/cert-manager-webhook"
    tag: "v1.0.4"
    pullPolicy: IfNotPresent

prometheus:
  enabled: true
  servicemonitor:
    enabled: ${service_monitor_enabled}
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}
