apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: istio-telemetry-mixer
spec:
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 0
    min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - projected
  - secret
  - emptyDir
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-telemetry-mixer-psp
  namespace: istio-system
rules:
- apiGroups:
  - policy
  resourceNames:
  - istio-telemetry-mixer
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: istio-telemetry-mixer-psp
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-telemetry-mixer-psp
subjects:
- kind: ServiceAccount
  name: istio-mixer-service-account
  namespace: istio-system
