---
version: '3.0'
services:
  semver-get-tags:
    image: dev-docker-rel-local.artifactory.aws.cloud.co.uk/semver:3.2.0
    env_file: .env
    entrypoint:
    - "/usr/bin/python3"
    - "/opt/app/src/semver/get_tags.py"
    working_dir: /opt/app
    volumes:
      - .:/opt/build:rw
