apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: allow-kiali-ingress
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector: {}
  - ports:
    - protocol: TCP
      port: 9090
    - protocol: TCP
      port: 20001
  podSelector:
    matchLabels:
      app: kiali
  policyTypes:
  - Ingress
