apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.operatorNamespace}}
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
    app: istiod
    name: {{.Values.operatorNamespace}}
    component: core-service
    part-of: eks-epaas
---
