apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{.Values.operatorNamespace}}
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'