kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-prometheus-ingress
  namespace: kube-system
spec:
  ingress:
  - ports:
    - port: 9153
      protocol: TCP
  - from:
    - namespaceSelector: {}
    - podSelector:
        matchLabels:
          app: prometheus
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
  - Ingress
