apiVersion: v1
name: self-signed-issuer
# The version and appVersion fields are set automatically by the release tool
version: v0.1.0
appVersion: v0.1.0
description: A Helm chart for cert-manager self-signed cluster issuer
