apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: epaas:executor
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - pods/status
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: epaas:executor
subjects:
- kind: Group
  name: epaas:executor
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: epaas:executor
  apiGroup: rbac.authorization.k8s.io
